#!/bin/bash

#------------------------------------------------------------
# Export the head of the basho-perf-scripts dir to the environment
#------------------------------------------------------------

SRCPATH=""
if [[ ${BASH_SOURCE[0]} == *"/"* ]]
then
    SRCPATH=${BASH_SOURCE[0]%/*}
    else
        SRCPATH=`dirname ${BASH_SOURCE[0]%/*}`
	fi

CWD="$( cd $SRCPATH; pwd )"

export RIAK_TEST_BASE=$CWD

#------------------------------------------------------------
# Add relevant directories to our python path
#------------------------------------------------------------

#export PYTHONPATH=${PYTHONPATH}:${RIAK_TEST_BASE}/python_scripts:/usr/local/lib/python2.7/site-packages

#------------------------------------------------------------
# Finally, source bash scripts
#------------------------------------------------------------

source $RIAK_TEST_BASE/bash_scripts/utilities.sh
source $RIAK_TEST_BASE/bash_scripts/riak_test_scripts.sh
source $RIAK_TEST_BASE/bash_scripts/basho_perf_scripts.sh


